先手後手番の作成
worldyone/discordpy-startup pull request #2
Opened 2021-01-23 18:23 UTC by snpc94

先手後手番の作成機能を追加しました。
ご確認お願いいたします。

2021-01-23 19:25 UTC, worldyone requested changes
decide_turnの変数名では、プレイヤー名が入ると想定できません。違和感があります。
また、decide_turn[0]が先手だと分かりません。同じくdecide_turn[1]が後手を表すとは想定できません。
sente, goteやfirst_player, second_player等の二つの変数名を定義するべきだと思います。

コミットメッセージですが、不適切だと思われます。
先手後手番が誰か分かるように実装したことを分かるようなコミットメッセージを残してください。
i.e. 先手後手番を自動で決定して表示する機能の作成

2021-02-06 16:32 UTC, snpc94 commented
先手後手番の自動決定機能について、ご指摘をもとに内容を修正いたしました。
変数については、first_move（先手）、second_move（後手）を採用しました。
コミット時のメッセージについても、実装したものがわかるようにいたしました。

2021-02-06 17:20 UTC, worldyone commented on kumiromicog.py
> +                turn = random.choice(turn_pattern)
turnという変数が先手と後手のプレイヤー名が入るリストになっていますが、名前に合っていると思いません。
具体的にはturn[0]が(先手 or 後手)のプレイヤー名であると想定できません。
違う変数名にして欲しいと、神であるエヒト様も仰られております。
なんならturn_patternも変えてね。

2021-02-06 17:21 UTC, worldyone commented on kumiromicog.py
> +                    "**先手**：" + str(first_move) + "　**後手**：" + str(second_move) + " になりました。"
str()で囲ってるけど、俺の想定が正しいともともと文字列なんだけど、必要あるのか？あるならいいけど。

2021-02-06 17:23 UTC, worldyone commented on kumiromicog.py
> +                #first_move：先手、second_move：後手
「#」の後にちょっと半角スペース入れてみる？入れた方がいいんじゃないかな、やっぱり。

2021-02-27 15:54 UTC, worldyone approved these changes

2021-02-27 15:54 UTC, merged